name: release

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  release:
    uses: parkerbxyz/.github/.github/workflows/release.yml@main
    with:
      app-id: ${{ vars.ACTIONS_APP_ID }}
    secrets:
      app-private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
